[package]
name = "emit_example_metric_prometheus"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.emit]
version = "1.17.1"
path = "../../"

[dependencies.emit_otlp]
version = "1.17.1"
path = "../../emitter/otlp"

[dependencies.rand]
version = "0.9"
