[package]
name = "emit_example_trace_zipkin"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.emit]
version = "1.16.2"
path = "../../"

[dependencies.emit_otlp]
version = "1.16.2"
path = "../../emitter/otlp"
