[package]
name = "emit_otlp_gen"
version = "0.0.0"
publish = false
edition = "2021"

[[bin]]
name = "gen"
path = "main.rs"

[dependencies.prost]
version = "0.14"

[dependencies.prost-build]
version = "0.14"
